name: Deploy to k3s

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn -q -DskipTests clean package

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export IMAGE var
        id: image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          GIT_SHA=$(echo "${{ github.sha }}" | head -c 7)
          IMAGE=ghcr.io/${OWNER}/ayuda-backend:${GIT_SHA}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push ${{ steps.image.outputs.IMAGE }}

      #       DESPLIEGUE DENTRO DE LA VM POR SSH
      - name: Deploy to k3s via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            IMAGE="${{ steps.image.outputs.IMAGE }}"
            echo "Usando kubeconfig interno del servidor"
            export KUBECONFIG=/home/azureuser/.kube/config

            echo "Actualizando Deployment ayuda-humanitaria de $IMAGE"

            kubectl set image deployment/ayuda-humanitaria ayuda-humanitaria=$IMAGE -n app-prod 
            kubectl patch deployment ayuda-humanitaria -n app-prod -p '{"spec":{"template":{"metadata":{"annotations":{"date":"'"$(date +%s)"'"}}}}}'

            echo "pull image and start pods"
            kubectl -n app-prod rollout restart deployment/ayuda-humanitaria

            echo "Esperando rollout..."
            kubectl rollout status deployment/ayuda-humanitaria -n app-prod --timeout=120s

            echo "Deployment completado"
